// Code generated by MockGen. DO NOT EDIT.
// Source: 0.cache.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/cocoide/tech-guide/pkg/domain/model/dto"
	repository "github.com/cocoide/tech-guide/pkg/domain/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// AddSortedSet mocks base method.
func (m *MockCacheRepo) AddSortedSet(key string, member interface{}, score float64, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSortedSet", key, member, score, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSortedSet indicates an expected call of AddSortedSet.
func (mr *MockCacheRepoMockRecorder) AddSortedSet(key, member, score, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSortedSet", reflect.TypeOf((*MockCacheRepo)(nil).AddSortedSet), key, member, score, expire)
}

// Delete mocks base method.
func (m *MockCacheRepo) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheRepoMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheRepo)(nil).Delete), key)
}

// ExtendExpiry mocks base method.
func (m *MockCacheRepo) ExtendExpiry(key string, extension time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendExpiry", key, extension)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendExpiry indicates an expected call of ExtendExpiry.
func (mr *MockCacheRepoMockRecorder) ExtendExpiry(key, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendExpiry", reflect.TypeOf((*MockCacheRepo)(nil).ExtendExpiry), key, extension)
}

// Get mocks base method.
func (m *MockCacheRepo) Get(key string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCacheRepoMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheRepo)(nil).Get), key)
}

// GetAllHashFields mocks base method.
func (m *MockCacheRepo) GetAllHashFields(key string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHashFields", key)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHashFields indicates an expected call of GetAllHashFields.
func (mr *MockCacheRepoMockRecorder) GetAllHashFields(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHashFields", reflect.TypeOf((*MockCacheRepo)(nil).GetAllHashFields), key)
}

// GetAllSortedSet mocks base method.
func (m *MockCacheRepo) GetAllSortedSet(key string) ([]dto.SortedSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSortedSet", key)
	ret0, _ := ret[0].([]dto.SortedSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSortedSet indicates an expected call of GetAllSortedSet.
func (mr *MockCacheRepoMockRecorder) GetAllSortedSet(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSortedSet", reflect.TypeOf((*MockCacheRepo)(nil).GetAllSortedSet), key)
}

// GetHashField mocks base method.
func (m *MockCacheRepo) GetHashField(key, fieldKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHashField", key, fieldKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHashField indicates an expected call of GetHashField.
func (mr *MockCacheRepoMockRecorder) GetHashField(key, fieldKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHashField", reflect.TypeOf((*MockCacheRepo)(nil).GetHashField), key, fieldKey)
}

// Set mocks base method.
func (m *MockCacheRepo) Set(key, value string, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheRepoMockRecorder) Set(key, value, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheRepo)(nil).Set), key, value, expire)
}

// SetHashField mocks base method.
func (m *MockCacheRepo) SetHashField(key string, field map[string]interface{}, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHashField", key, field, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHashField indicates an expected call of SetHashField.
func (mr *MockCacheRepoMockRecorder) SetHashField(key, field, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHashField", reflect.TypeOf((*MockCacheRepo)(nil).SetHashField), key, field, expire)
}

// Update mocks base method.
func (m *MockCacheRepo) Update(key, value string, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", key, value, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCacheRepoMockRecorder) Update(key, value, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCacheRepo)(nil).Update), key, value, expire)
}

// WithCtx mocks base method.
func (m *MockCacheRepo) WithCtx(ctx context.Context) repository.CacheRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCtx", ctx)
	ret0, _ := ret[0].(repository.CacheRepo)
	return ret0
}

// WithCtx indicates an expected call of WithCtx.
func (mr *MockCacheRepoMockRecorder) WithCtx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCtx", reflect.TypeOf((*MockCacheRepo)(nil).WithCtx), ctx)
}
