// Code generated by MockGen. DO NOT EDIT.
// Source: topic.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	time "time"

	model "github.com/cocoide/tech-guide/pkg/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockTopicRepo is a mock of TopicRepo interface.
type MockTopicRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepoMockRecorder
}

// MockTopicRepoMockRecorder is the mock recorder for MockTopicRepo.
type MockTopicRepoMockRecorder struct {
	mock *MockTopicRepo
}

// NewMockTopicRepo creates a new mock instance.
func NewMockTopicRepo(ctrl *gomock.Controller) *MockTopicRepo {
	mock := &MockTopicRepo{ctrl: ctrl}
	mock.recorder = &MockTopicRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepo) EXPECT() *MockTopicRepoMockRecorder {
	return m.recorder
}

// CreateTopics mocks base method.
func (m *MockTopicRepo) CreateTopics(topics []model.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopics", topics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopics indicates an expected call of CreateTopics.
func (mr *MockTopicRepoMockRecorder) CreateTopics(topics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopics", reflect.TypeOf((*MockTopicRepo)(nil).CreateTopics), topics)
}

// DoFollowTopic mocks base method.
func (m *MockTopicRepo) DoFollowTopic(accountID, topicID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoFollowTopic", accountID, topicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoFollowTopic indicates an expected call of DoFollowTopic.
func (mr *MockTopicRepoMockRecorder) DoFollowTopic(accountID, topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoFollowTopic", reflect.TypeOf((*MockTopicRepo)(nil).DoFollowTopic), accountID, topicID)
}

// GetAllTopics mocks base method.
func (m *MockTopicRepo) GetAllTopics() ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTopics")
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTopics indicates an expected call of GetAllTopics.
func (mr *MockTopicRepoMockRecorder) GetAllTopics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTopics", reflect.TypeOf((*MockTopicRepo)(nil).GetAllTopics))
}

// GetCategories mocks base method.
func (m *MockTopicRepo) GetCategories() ([]model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories")
	ret0, _ := ret[0].([]model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockTopicRepoMockRecorder) GetCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockTopicRepo)(nil).GetCategories))
}

// GetCategoriesWithTopics mocks base method.
func (m *MockTopicRepo) GetCategoriesWithTopics() ([]model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesWithTopics")
	ret0, _ := ret[0].([]model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesWithTopics indicates an expected call of GetCategoriesWithTopics.
func (mr *MockTopicRepoMockRecorder) GetCategoriesWithTopics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesWithTopics", reflect.TypeOf((*MockTopicRepo)(nil).GetCategoriesWithTopics))
}

// GetFollowingTopicIDs mocks base method.
func (m *MockTopicRepo) GetFollowingTopicIDs(accountID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingTopicIDs", accountID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingTopicIDs indicates an expected call of GetFollowingTopicIDs.
func (mr *MockTopicRepoMockRecorder) GetFollowingTopicIDs(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingTopicIDs", reflect.TypeOf((*MockTopicRepo)(nil).GetFollowingTopicIDs), accountID)
}

// GetFollowingTopics mocks base method.
func (m *MockTopicRepo) GetFollowingTopics(accountId int) ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingTopics", accountId)
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingTopics indicates an expected call of GetFollowingTopics.
func (mr *MockTopicRepoMockRecorder) GetFollowingTopics(accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingTopics", reflect.TypeOf((*MockTopicRepo)(nil).GetFollowingTopics), accountId)
}

// GetPopularTopics mocks base method.
func (m *MockTopicRepo) GetPopularTopics(limit int) ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularTopics", limit)
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularTopics indicates an expected call of GetPopularTopics.
func (mr *MockTopicRepoMockRecorder) GetPopularTopics(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularTopics", reflect.TypeOf((*MockTopicRepo)(nil).GetPopularTopics), limit)
}

// GetRecentPopularArticleIDs mocks base method.
func (m *MockTopicRepo) GetRecentPopularArticleIDs(duration time.Duration, limit int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentPopularArticleIDs", duration, limit)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentPopularArticleIDs indicates an expected call of GetRecentPopularArticleIDs.
func (mr *MockTopicRepoMockRecorder) GetRecentPopularArticleIDs(duration, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentPopularArticleIDs", reflect.TypeOf((*MockTopicRepo)(nil).GetRecentPopularArticleIDs), duration, limit)
}

// GetTopicData mocks base method.
func (m *MockTopicRepo) GetTopicData(topicID int) (*model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicData", topicID)
	ret0, _ := ret[0].(*model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicData indicates an expected call of GetTopicData.
func (mr *MockTopicRepoMockRecorder) GetTopicData(topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicData", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicData), topicID)
}

// GetTopicToArticleArrayByArticleID mocks base method.
func (m *MockTopicRepo) GetTopicToArticleArrayByArticleID(articleID int) ([]model.TopicsToArticles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicToArticleArrayByArticleID", articleID)
	ret0, _ := ret[0].([]model.TopicsToArticles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicToArticleArrayByArticleID indicates an expected call of GetTopicToArticleArrayByArticleID.
func (mr *MockTopicRepoMockRecorder) GetTopicToArticleArrayByArticleID(articleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicToArticleArrayByArticleID", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicToArticleArrayByArticleID), articleID)
}

// GetTopicToArticleArrayByArticleIDs mocks base method.
func (m *MockTopicRepo) GetTopicToArticleArrayByArticleIDs(articleIDs []int) ([]model.TopicsToArticles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicToArticleArrayByArticleIDs", articleIDs)
	ret0, _ := ret[0].([]model.TopicsToArticles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicToArticleArrayByArticleIDs indicates an expected call of GetTopicToArticleArrayByArticleIDs.
func (mr *MockTopicRepoMockRecorder) GetTopicToArticleArrayByArticleIDs(articleIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicToArticleArrayByArticleIDs", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicToArticleArrayByArticleIDs), articleIDs)
}

// GetTopicsByCategoryIDs mocks base method.
func (m *MockTopicRepo) GetTopicsByCategoryIDs(categoryIds []int) ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsByCategoryIDs", categoryIds)
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsByCategoryIDs indicates an expected call of GetTopicsByCategoryIDs.
func (mr *MockTopicRepoMockRecorder) GetTopicsByCategoryIDs(categoryIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsByCategoryIDs", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicsByCategoryIDs), categoryIds)
}

// GetTopicsByCollectionID mocks base method.
func (m *MockTopicRepo) GetTopicsByCollectionID(collectionID int) ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsByCollectionID", collectionID)
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsByCollectionID indicates an expected call of GetTopicsByCollectionID.
func (mr *MockTopicRepoMockRecorder) GetTopicsByCollectionID(collectionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsByCollectionID", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicsByCollectionID), collectionID)
}

// GetTopicsByIDs mocks base method.
func (m *MockTopicRepo) GetTopicsByIDs(IDs []int) ([]model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsByIDs", IDs)
	ret0, _ := ret[0].([]model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsByIDs indicates an expected call of GetTopicsByIDs.
func (mr *MockTopicRepoMockRecorder) GetTopicsByIDs(IDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsByIDs", reflect.TypeOf((*MockTopicRepo)(nil).GetTopicsByIDs), IDs)
}

// IsFollowingTopic mocks base method.
func (m *MockTopicRepo) IsFollowingTopic(accountID, topicID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowingTopic", accountID, topicID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowingTopic indicates an expected call of IsFollowingTopic.
func (mr *MockTopicRepoMockRecorder) IsFollowingTopic(accountID, topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowingTopic", reflect.TypeOf((*MockTopicRepo)(nil).IsFollowingTopic), accountID, topicID)
}

// UnfollowTopic mocks base method.
func (m *MockTopicRepo) UnfollowTopic(accountID, topicID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowTopic", accountID, topicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowTopic indicates an expected call of UnfollowTopic.
func (mr *MockTopicRepoMockRecorder) UnfollowTopic(accountID, topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowTopic", reflect.TypeOf((*MockTopicRepo)(nil).UnfollowTopic), accountID, topicID)
}
