version: "3"
services:
  app:
    container_name: tech-guide-deploy
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
    command: ./main
    
  dev:
    container_name: tech-guide-develop
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: devlop
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  db:
    container_name: tech-guide-db
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: kazuki
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: volume
        source: tech-guide-volume
        target: /var/lib/mysql
  redis:
    container_name: tech-guide-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
    - type: volume
      source: tech-guide-volume
      target: /data
volumes:
  tech-guide-volume:
    name: tech-guide-mysql