FROM golang:1.19-alpine AS develop

WORKDIR /app
RUN go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN go install github.com/cosmtrek/air@latest
CMD ["air", "-c", "conf/.air.toml"]