# fly.toml app configuration file generated for tech-guide-scheduler on 2023-11-20T11:47:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tech-guide-scheduler"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
