name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
    paths-ignore:
      - 'backend/docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
    paths-ignore:
      - 'backend/docs/**'

env:
  cache-version: v1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.cache-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.cache-version }}-

      - name: Get dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Test
        run: cd backend && go test ./test/.