CREATE TABLE IF NOT EXISTS accounts(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NULL,
  display_name VARCHAR(30) NOT NULL,
  avatar_url VARCHAR(255) NULL
)